import { useState, type ComponentType } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useLocation, useSearch, Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import {
  Calendar,
  Clock,
  AlertTriangle,
  Phone,
  Mail,
  ExternalLink,
  Zap,
  CheckCircle2,
  ArrowLeft,
  FileText,
  Package,
  Plus,
  UserPlus,
  X,
  ArrowUpDown,
  MailOpen,
  List,
  Loader2,
  FlaskConical,
  Building2,
  Receipt,
  Tag,
  Circle,
  CheckCheck,
  ChevronRight,
  SlidersHorizontal,
} from "lucide-react";
import { format, isToday, isPast, isThisWeek } from "date-fns";

interface UnifiedTask {
  id: number | string;
  customerId?: string | null;
  leadId?: number | null;
  recordType?: "customer" | "lead" | null;
  recordId?: string | number | null;
  recordName?: string;
  source: "calendar" | "spotlight";
  category: "today" | "overdue";
  title: string;
  description?: string;
  taskType?: string;
  dueDate?: string;
  priority?: string;
  status: string;
  customerName: string;
  skippedAt?: string;
  assignedToName?: string;
  isAutoGenerated?: boolean;
  contactEmail?: string | null;
}

interface TaskSummary {
  today: number;
  overdue: number;
  pending: number;
  email: number;
  emailsNotReplied: number;
  seqFollowUp: number;
  pressTestSent: number;
  spotlightSkipped: number;
  spotlightRemaining: number;
  spotlightCompleted: number;
  spotlightTarget: number;
}

interface PressTestEntry {
  id: string;
  source: "label_print" | "lead_manual" | "odoo_sale_order" | "odoo_invoice";
  contactName: string;
  customerId?: string | null;
  leadId?: number | null;
  sentAt?: string | null;
  notes?: string | null;
  sentByName?: string | null;
  quantity?: number | null;
  orderNumber?: string | null;
  odooId?: number | null;
  odooModel?: string | null;
  odooUrl?: string | null;
}

interface EmailNotReplied {
  id: number | string;
  subject: string;
  sentAt: string;
  sentBy?: string | null;
  recipientEmail?: string | null;
  recipientName?: string | null;
  contactName: string;
  customerId?: string | null;
  leadId?: number | null;
  recordType?: string | null;
  recordId?: string | number | null;
  daysSinceSent: number;
  source?: string;
}

interface ContactSearchLead {
  id: number;
  name: string;
  company?: string | null;
}

interface ContactSearchCustomer {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  email?: string | null;
}

interface CreateTaskPayload {
  title: string;
  description: string;
  taskType: string;
  priority: string;
  dueDate: string;
  leadId?: number;
  customerId?: string;
}

interface SeqFollowUp {
  id: number;
  campaignName: string;
  completedAt: string;
  contactName: string;
  customerId?: string | null;
  leadId?: number | null;
  recordType?: string | null;
  recordId?: string | number | null;
}

interface CreateTaskForm {
  title: string;
  description: string;
  taskType: string;
  priority: string;
  dueDate: string;
  leadId: string;
  customerId: string;
}

export default function TaskInboxPage() {
  const [, setLocation] = useLocation();
  const searchString = useSearch();
  const params = new URLSearchParams(searchString);

  const [activeTab, setActiveTab] = useState(params.get("filter") || "pending");
  const [sort, setSort] = useState(params.get("sort") || "due_asc");
  const [typeFilter, setTypeFilter] = useState(params.get("type") || "all");
  const [assigneeFilter, setAssigneeFilter] = useState(params.get("assignee") || "all");
  const [priorityFilter, setPriorityFilter] = useState(params.get("priority") || "all");
  const [showFilters, setShowFilters] = useState(false);

  const [selectedTask, setSelectedTask] = useState<UnifiedTask | null>(null);
  const [showSpotlightPrompt, setShowSpotlightPrompt] = useState(false);
  const [showTaskDetail, setShowTaskDetail] = useState(false);
  const [showCreateTask, setShowCreateTask] = useState(false);
  const [contactSearch, setContactSearch] = useState("");
  const [createForm, setCreateForm] = useState<CreateTaskForm>({
    title: "",
    description: "",
    taskType: "call",
    priority: "normal",
    dueDate: "",
    leadId: "",
    customerId: "",
  });

  const { toast } = useToast();
  const queryClient = useQueryClient();
  const { user: currentUser } = useAuth();
  const currentUserEmail = currentUser?.email?.toLowerCase() || '';

  const updateUrl = (tab: string, s: string, type?: string, assignee?: string, priority?: string) => {
    const p = new URLSearchParams();
    p.set("filter", tab);
    p.set("sort", s);
    const t = type ?? typeFilter;
    const a = assignee ?? assigneeFilter;
    const pr = priority ?? priorityFilter;
    if (t && t !== "all") p.set("type", t);
    if (a && a !== "all") p.set("assignee", a);
    if (pr && pr !== "all") p.set("priority", pr);
    setLocation(`/tasks?${p.toString()}`, { replace: true });
  };

  const handleTabChange = (tab: string) => {
    setActiveTab(tab);
    updateUrl(tab, sort);
  };

  const { data: summary } = useQuery<TaskSummary>({
    queryKey: ["/api/tasks/summary"],
  });

  const { data: tasks, isLoading: tasksLoading } = useQuery<UnifiedTask[]>({
    queryKey: ["/api/tasks/list", activeTab, sort, typeFilter, assigneeFilter, priorityFilter],
    queryFn: async () => {
      const p = new URLSearchParams({ filter: activeTab, sort });
      if (typeFilter && typeFilter !== "all") p.set("type", typeFilter);
      if (assigneeFilter && assigneeFilter !== "all") p.set("assignee", assigneeFilter);
      if (priorityFilter && priorityFilter !== "all") p.set("priority", priorityFilter);
      const res = await fetch(`/api/tasks/list?${p.toString()}`);
      if (!res.ok) throw new Error("Failed to fetch tasks");
      return res.json();
    },
    enabled: activeTab !== "emails" && activeTab !== "seq" && activeTab !== "press_test",
  });

  const { data: emailsNotReplied, isLoading: emailsLoading } = useQuery<EmailNotReplied[]>({
    queryKey: ["/api/tasks/emails-not-replied"],
    enabled: activeTab === "emails",
  });

  const { data: seqFollowUps, isLoading: seqLoading } = useQuery<SeqFollowUp[]>({
    queryKey: ["/api/tasks/seq-followups"],
    enabled: activeTab === "seq",
  });

  const { data: pressTestEntries, isLoading: pressTestLoading } = useQuery<PressTestEntry[]>({
    queryKey: ["/api/tasks/press-test-sent"],
    enabled: activeTab === "press_test",
  });

  const { data: contactSearchResults, isLoading: contactSearchLoading } = useQuery<{leads: ContactSearchLead[], customers: ContactSearchCustomer[]}>({
    queryKey: ["/api/tasks/contact-search", contactSearch],
    queryFn: async () => {
      if (contactSearch.trim().length < 2) return { leads: [], customers: [] };
      const [leadsRes, customersRes] = await Promise.all([
        fetch(`/api/leads?search=${encodeURIComponent(contactSearch)}&limit=5`).then(r => r.json()),
        fetch(`/api/customers?search=${encodeURIComponent(contactSearch)}&limit=5&paginated=true`).then(r => r.json()),
      ]);
      const leads = Array.isArray(leadsRes) ? leadsRes : (leadsRes.leads ?? leadsRes.data ?? []);
      const customers = Array.isArray(customersRes) ? customersRes : (customersRes.customers ?? []);
      return { leads: leads.slice(0, 5), customers: customers.slice(0, 5) };
    },
    enabled: contactSearch.trim().length >= 2,
  });

  const removeTaskFromCache = (taskId: number) => {
    queryClient.setQueriesData<UnifiedTask[]>(
      { queryKey: ["/api/tasks/list"], exact: false },
      (old) => (old ? old.filter((t) => t.id !== taskId) : old)
    );
  };

  const completeTaskMutation = useMutation({
    mutationFn: async (taskId: number) =>
      apiRequest("POST", `/api/tasks/${taskId}/complete`, { notes: "Completed from task inbox" }),
    onMutate: (taskId) => {
      removeTaskFromCache(taskId);
      setShowTaskDetail(false);
      setSelectedTask(null);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/list"] });
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/summary"] });
      toast({ title: "Task completed" });
    },
    onError: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/list"] });
      toast({ title: "Failed to complete task", variant: "destructive" });
    },
  });

  const cancelTaskMutation = useMutation({
    mutationFn: async (taskId: number) => apiRequest("DELETE", `/api/tasks/${taskId}`),
    onMutate: (taskId) => {
      removeTaskFromCache(taskId);
      setShowTaskDetail(false);
      setSelectedTask(null);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/list"] });
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/summary"] });
      toast({ title: "Task cancelled" });
    },
    onError: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/list"] });
      toast({ title: "Failed to cancel task", variant: "destructive" });
    },
  });

  const addToLeadsMutation = useMutation({
    mutationFn: async ({ email, name }: { email: string; name: string }) => {
      const res = await apiRequest("POST", "/api/leads", {
        name,
        email,
        sourceType: "manual",
        stage: "new",
      });
      return res.json();
    },
    onSuccess: (lead) => {
      toast({ title: "Lead created", description: `${lead.name} added to leads` });
      setLocation(`/leads/${lead.id}`);
    },
    onError: () => {
      toast({ title: "Failed to create lead", variant: "destructive" });
    },
  });

  const createTaskMutation = useMutation({
    mutationFn: async (data: CreateTaskPayload) => {
      const res = await apiRequest("POST", "/api/tasks", data);
      if (!res.ok) throw new Error("Failed to create task");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/list"] });
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/summary"] });
      toast({ title: "Task created" });
      setShowCreateTask(false);
      setCreateForm({ title: "", description: "", taskType: "call", priority: "normal", dueDate: "", leadId: "", customerId: "" });
      setContactSearch("");
    },
    onError: (e: Error) => toast({ title: "Failed to create task", description: e.message, variant: "destructive" }),
  });

  const createEmailTaskMutation = useMutation({
    mutationFn: async (emailSendId: number | string) => {
      const res = await apiRequest("POST", `/api/tasks/emails-not-replied/${emailSendId}/create-task`, {});
      if (!res.ok) throw new Error("Failed to create task");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/emails-not-replied"] });
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/summary"] });
      queryClient.invalidateQueries({ queryKey: ["/api/tasks/list"] });
      toast({ title: "Follow-up task created" });
    },
    onError: (e: Error) => toast({ title: "Failed", description: e.message, variant: "destructive" }),
  });

  const getTaskTypeIcon = (taskType: string | undefined) => {
    if (!taskType) return Clock;
    if (taskType.includes("quote")) return FileText;
    if (taskType.includes("sample")) return Package;
    if (taskType.includes("call")) return Phone;
    if (taskType.includes("email")) return Mail;
    if (taskType.includes("spotlight")) return Zap;
    return Clock;
  };

  const getPriorityDot = (priority: string | undefined) => {
    switch (priority) {
      case "urgent": return "bg-red-500";
      case "high": return "bg-orange-400";
      case "normal": return "bg-blue-400";
      case "low": return "bg-gray-300";
      default: return "bg-gray-300";
    }
  };

  const getDueDateStyle = (task: UnifiedTask) => {
    if (!task.dueDate) return { text: "", className: "text-gray-400" };
    const d = new Date(task.dueDate);
    if (isPast(d) && !isToday(d)) return { text: format(d, "MMM d"), className: "text-red-500 font-medium" };
    if (isToday(d)) return { text: "Today", className: "text-amber-600 font-medium" };
    if (isThisWeek(d)) return { text: format(d, "EEE"), className: "text-orange-500" };
    return { text: format(d, "MMM d"), className: "text-gray-500" };
  };

  const getRecordLink = (task: UnifiedTask) => {
    if (task.recordType === "lead" && task.recordId) return `/leads/${task.recordId}`;
    if (task.recordType === "customer" && task.recordId) return `/odoo-contacts/${task.recordId}`;
    if (task.customerId) return `/odoo-contacts/${task.customerId}`;
    return null;
  };

  const handleTaskClick = (task: UnifiedTask) => {
    setSelectedTask(task);
    if (task.source === "spotlight") {
      setShowSpotlightPrompt(true);
    } else {
      setShowTaskDetail(true);
    }
  };

  const handleSubmitCreateTask = () => {
    const { title, taskType, dueDate, leadId, customerId } = createForm;
    if (!title.trim() || !taskType || !dueDate) {
      toast({ title: "Missing fields", description: "Title, type, and due date are required.", variant: "destructive" });
      return;
    }
    if (!leadId && !customerId) {
      toast({ title: "Missing contact", description: "Please assign to a lead or customer.", variant: "destructive" });
      return;
    }
    createTaskMutation.mutate({
      ...createForm,
      leadId: leadId ? Number(leadId) : undefined,
      customerId: customerId || undefined,
    });
  };

  const isLoading = activeTab === "emails" ? emailsLoading : activeTab === "seq" ? seqLoading : activeTab === "press_test" ? pressTestLoading : tasksLoading;
  const isStandardTab = activeTab !== "emails" && activeTab !== "seq" && activeTab !== "press_test";
  const hasActiveFilters = typeFilter !== "all" || assigneeFilter !== "all" || priorityFilter !== "all";

  const navItems = [
    {
      group: "Tasks",
      items: [
        { key: "pending", label: "All Tasks", count: summary?.pending, icon: CheckCheck, countColor: "" },
        { key: "today", label: "Due Today", count: summary?.today, icon: Calendar, countColor: (summary?.today || 0) > 0 ? "bg-amber-100 text-amber-700" : "" },
        { key: "overdue", label: "Overdue", count: summary?.overdue, icon: AlertTriangle, countColor: (summary?.overdue || 0) > 0 ? "bg-red-100 text-red-700" : "" },
        { key: "email", label: "Email Tasks", count: summary?.email, icon: Mail, countColor: "" },
      ],
    },
    {
      group: "Inbox",
      items: [
        { key: "emails", label: "Emails Not Replied", count: summary?.emailsNotReplied, icon: MailOpen, countColor: (summary?.emailsNotReplied || 0) > 0 ? "bg-orange-100 text-orange-700" : "" },
        { key: "seq", label: "Seq Follow-up", count: summary?.seqFollowUp, icon: List, countColor: (summary?.seqFollowUp || 0) > 0 ? "bg-purple-100 text-purple-700" : "" },
        { key: "press_test", label: "Press Test Sent", count: summary?.pressTestSent, icon: FlaskConical, countColor: "" },
      ],
    },
  ];

  const sectionTitle: Record<string, string> = {
    pending: "All Tasks",
    today: "Due Today",
    overdue: "Overdue",
    email: "Email Tasks",
    emails: "Emails Not Replied",
    seq: "Email Sequence — Call Follow Up",
    press_test: "Press Test Sheets Sent",
  };

  return (
    <div className="h-screen bg-white flex flex-col overflow-hidden">
      {/* Top Header */}
      <div className="border-b border-gray-200 px-4 py-3 flex items-center justify-between flex-shrink-0 bg-white">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={() => setLocation("/")} className="text-gray-500 hover:text-gray-700 -ml-1">
            <ArrowLeft className="h-4 w-4 mr-1" />
            Back
          </Button>
          <div className="h-4 w-px bg-gray-200" />
          <h1 className="text-base font-semibold text-gray-900">Tasks</h1>
        </div>
        <Button size="sm" onClick={() => setShowCreateTask(true)} className="gap-1.5 h-8">
          <Plus className="h-3.5 w-3.5" />
          New Task
        </Button>
      </div>

      {/* Body */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left Sidebar */}
        <div className="w-56 border-r border-gray-200 bg-gray-50/60 flex-shrink-0 overflow-y-auto">
          <div className="py-3 px-2">
            {navItems.map((group) => (
              <div key={group.group} className="mb-4">
                <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider px-2 mb-1">{group.group}</p>
                {group.items.map(({ key, label, count, icon: Icon, countColor }) => (
                  <button
                    key={key}
                    onClick={() => handleTabChange(key)}
                    className={`w-full flex items-center justify-between px-2 py-1.5 rounded-md text-sm transition-colors mb-0.5 ${
                      activeTab === key
                        ? "bg-white shadow-sm border border-gray-200 text-gray-900 font-medium"
                        : "text-gray-600 hover:bg-white/70 hover:text-gray-900"
                    }`}
                  >
                    <span className="flex items-center gap-2">
                      <Icon className="h-3.5 w-3.5 flex-shrink-0" />
                      <span className="truncate text-xs">{label}</span>
                    </span>
                    {(count || 0) > 0 && (
                      <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded-full flex-shrink-0 ${countColor || "bg-gray-100 text-gray-600"}`}>
                        {count}
                      </span>
                    )}
                  </button>
                ))}
              </div>
            ))}
          </div>
        </div>

        {/* Main Content */}
        <div className="flex-1 flex flex-col overflow-hidden bg-white">
          {/* Content Header */}
          <div className="border-b border-gray-100 px-5 py-3 flex items-center justify-between flex-shrink-0">
            <h2 className="text-sm font-semibold text-gray-800">{sectionTitle[activeTab] || "Tasks"}</h2>
            {isStandardTab && (
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  className={`h-7 text-xs gap-1.5 ${showFilters ? "bg-gray-100" : ""}`}
                  onClick={() => setShowFilters(!showFilters)}
                >
                  <SlidersHorizontal className="h-3.5 w-3.5" />
                  Filter
                  {hasActiveFilters && <span className="h-1.5 w-1.5 rounded-full bg-blue-500 flex-shrink-0" />}
                </Button>
                <Select value={sort} onValueChange={(v) => { setSort(v); updateUrl(activeTab, v); }}>
                  <SelectTrigger className="h-7 w-40 text-xs border-gray-200">
                    <ArrowUpDown className="h-3 w-3 mr-1.5 text-gray-400" />
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="due_asc">Due: Soonest First</SelectItem>
                    <SelectItem value="due_desc">Due: Latest First</SelectItem>
                    <SelectItem value="priority">Priority</SelectItem>
                    <SelectItem value="created">Recently Created</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>

          {/* Filter Bar */}
          {showFilters && isStandardTab && (
            <div className="border-b border-gray-100 px-5 py-2.5 bg-gray-50/50 flex items-center gap-4 flex-shrink-0">
              <div className="flex items-center gap-2">
                <span className="text-xs text-gray-500">Type</span>
                <Select value={typeFilter} onValueChange={(v) => { setTypeFilter(v); updateUrl(activeTab, sort, v); }}>
                  <SelectTrigger className="h-6 w-32 text-xs border-gray-200">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Types</SelectItem>
                    <SelectItem value="call">Call</SelectItem>
                    <SelectItem value="email">Email</SelectItem>
                    <SelectItem value="quote">Quote Follow-up</SelectItem>
                    <SelectItem value="sample">Sample</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs text-gray-500">Priority</span>
                <Select value={priorityFilter} onValueChange={(v) => { setPriorityFilter(v); updateUrl(activeTab, sort, undefined, undefined, v); }}>
                  <SelectTrigger className="h-6 w-24 text-xs border-gray-200">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All</SelectItem>
                    <SelectItem value="urgent">Urgent</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="normal">Normal</SelectItem>
                    <SelectItem value="low">Low</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs text-gray-500">Assignee</span>
                <Select value={assigneeFilter} onValueChange={(v) => { setAssigneeFilter(v); updateUrl(activeTab, sort, undefined, v); }}>
                  <SelectTrigger className="h-6 w-24 text-xs border-gray-200">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Reps</SelectItem>
                    <SelectItem value="me">Just Me</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              {hasActiveFilters && (
                <button
                  className="text-xs text-blue-500 hover:text-blue-700 flex items-center gap-1"
                  onClick={() => { setTypeFilter("all"); setAssigneeFilter("all"); setPriorityFilter("all"); updateUrl(activeTab, sort, "all", "all", "all"); }}
                >
                  <X className="h-3 w-3" /> Clear filters
                </button>
              )}
            </div>
          )}

          {/* Task List */}
          <ScrollArea className="flex-1">
            <div className="px-5">
              {isLoading ? (
                <div className="flex items-center justify-center h-40">
                  <Loader2 className="h-5 w-5 animate-spin text-gray-300" />
                </div>
              ) : activeTab === "emails" ? (
                <EmailsNotRepliedList
                  items={emailsNotReplied}
                  onCreateTask={(id) => createEmailTaskMutation.mutate(id)}
                  isPending={createEmailTaskMutation.isPending}
                />
              ) : activeTab === "seq" ? (
                <SeqFollowUpList items={seqFollowUps} />
              ) : activeTab === "press_test" ? (
                <PressTestList items={pressTestEntries} />
              ) : tasks && tasks.length > 0 ? (
                <TaskRows
                  tasks={tasks}
                  onTaskClick={handleTaskClick}
                  onComplete={(id) => completeTaskMutation.mutate(id)}
                  isCompletePending={completeTaskMutation.isPending}
                  getTaskTypeIcon={getTaskTypeIcon}
                  getPriorityDot={getPriorityDot}
                  getDueDateStyle={getDueDateStyle}
                />
              ) : (
                <EmptyState icon={CheckCircle2} title="All caught up!" description="No tasks in this category." />
              )}
            </div>
          </ScrollArea>
        </div>
      </div>

      {/* Spotlight Prompt Dialog */}
      <Dialog open={showSpotlightPrompt} onOpenChange={setShowSpotlightPrompt}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Zap className="h-5 w-5 text-purple-600" />
              SPOTLIGHT Task
            </DialogTitle>
            <DialogDescription>
              This is a SPOTLIGHT task for <strong>{selectedTask?.customerName}</strong>. Enter SPOTLIGHT mode for the best workflow experience.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="flex gap-2">
            <Button variant="outline" onClick={() => { setShowSpotlightPrompt(false); setShowTaskDetail(true); }}>
              View Details Only
            </Button>
            <Button onClick={() => { setShowSpotlightPrompt(false); setLocation("/"); }} className="bg-purple-600 hover:bg-purple-700">
              <Zap className="h-4 w-4 mr-2" />
              Enter SPOTLIGHT Mode
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Task Detail Dialog */}
      <Dialog open={showTaskDetail} onOpenChange={setShowTaskDetail}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>{selectedTask?.title}</DialogTitle>
            <DialogDescription>{selectedTask?.description || "No description provided"}</DialogDescription>
          </DialogHeader>

          {selectedTask && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <p className="text-muted-foreground text-xs mb-1">
                    {selectedTask.recordType === "lead" ? "Lead" : "Customer"}
                  </p>
                  {(() => {
                    const name = selectedTask.recordName || selectedTask.customerName;
                    const isUnknown = !name || name === 'Unknown';
                    return isUnknown && selectedTask.contactEmail ? (
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-medium text-gray-500">{selectedTask.contactEmail}</span>
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-6 text-xs px-2 gap-1 text-green-700 border-green-200 hover:bg-green-50"
                          onClick={() => addToLeadsMutation.mutate({ email: selectedTask.contactEmail!, name: selectedTask.contactEmail! })}
                          disabled={addToLeadsMutation.isPending}
                        >
                          <UserPlus className="h-3 w-3" />
                          Add to Leads
                        </Button>
                      </div>
                    ) : (
                      <p className="font-medium">{name}</p>
                    );
                  })()}
                </div>
                <div>
                  <p className="text-muted-foreground text-xs mb-1">Type</p>
                  <p className="font-medium capitalize">{selectedTask.taskType?.replace(/_/g, " ") || "General"}</p>
                </div>
                {selectedTask.dueDate && (
                  <div>
                    <p className="text-muted-foreground text-xs mb-1">Due Date</p>
                    <p className="font-medium">{format(new Date(selectedTask.dueDate), "MMM d, yyyy")}</p>
                  </div>
                )}
                {selectedTask.priority && (
                  <div>
                    <p className="text-muted-foreground text-xs mb-1">Priority</p>
                    <span className="capitalize text-sm font-medium">{selectedTask.priority}</span>
                  </div>
                )}
                {selectedTask.assignedToName && (
                  <div>
                    <p className="text-muted-foreground text-xs mb-1">Assigned To</p>
                    <p className="font-medium">{selectedTask.assignedToName}</p>
                  </div>
                )}
              </div>

              <div className="flex flex-wrap gap-2 pt-4 border-t">
                {(() => {
                  const link = getRecordLink(selectedTask);
                  return link ? (
                    <Link href={link}>
                      <Button variant="outline" size="sm" className="gap-2">
                        <ExternalLink className="h-4 w-4" />
                        View {selectedTask.recordType === "lead" ? "Lead" : "Customer"}
                      </Button>
                    </Link>
                  ) : null;
                })()}
                {(selectedTask.contactEmail || selectedTask.taskType === 'email_engagement') && (() => {
                  // For email engagement tasks, only show Go to Gmail if the email was sent by the current user
                  const sentBy = selectedTask.assignedTo?.toLowerCase();
                  if (selectedTask.taskType === 'email_engagement' && sentBy && sentBy !== currentUserEmail) return null;

                  let gmailSearch = '';
                  if (selectedTask.taskType === 'email_engagement') {
                    // Strip "Email Opened: " / "Email Link Clicked: " prefix to get the exact subject
                    const subject = selectedTask.title
                      .replace(/^Email Opened:\s*/i, '')
                      .replace(/^Email Link Clicked:\s*/i, '');
                    // Combine subject + recipient email to pinpoint the exact email thread
                    gmailSearch = selectedTask.contactEmail
                      ? `subject:"${subject}" (to:${selectedTask.contactEmail} OR from:${selectedTask.contactEmail})`
                      : `subject:"${subject}"`;
                  } else if (selectedTask.contactEmail) {
                    gmailSearch = `from:${selectedTask.contactEmail} OR to:${selectedTask.contactEmail}`;
                  }
                  if (!gmailSearch) return null;
                  return (
                    <a
                      href={`https://mail.google.com/mail/u/0/#search/${encodeURIComponent(gmailSearch)}`}
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <Button variant="outline" size="sm" className="gap-2 text-blue-600 border-blue-200 hover:bg-blue-50">
                        <Mail className="h-4 w-4" />
                        Go to Gmail
                      </Button>
                    </a>
                  );
                })()}
                {selectedTask.source === "calendar" && typeof selectedTask.id === "number" && (
                  <>
                    <Button
                      size="sm"
                      onClick={() => completeTaskMutation.mutate(selectedTask.id as number)}
                      disabled={completeTaskMutation.isPending}
                      className="gap-2"
                    >
                      <CheckCircle2 className="h-4 w-4" />
                      Complete
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => cancelTaskMutation.mutate(selectedTask.id as number)}
                      disabled={cancelTaskMutation.isPending}
                      className="gap-2 text-red-600 border-red-200 hover:bg-red-50"
                    >
                      <X className="h-4 w-4" />
                      Cancel Task
                    </Button>
                  </>
                )}
                {selectedTask.source === "spotlight" && (
                  <Button onClick={() => { setShowTaskDetail(false); setLocation("/"); }} className="gap-2 bg-purple-600 hover:bg-purple-700" size="sm">
                    <Zap className="h-4 w-4" />
                    Enter SPOTLIGHT
                  </Button>
                )}
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Create Task Dialog */}
      <Dialog open={showCreateTask} onOpenChange={setShowCreateTask}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Create New Task</DialogTitle>
            <DialogDescription>Assign a task to a lead or customer.</DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <Label className="text-xs">Title *</Label>
              <Input
                placeholder="Task title..."
                value={createForm.title}
                onChange={(e) => setCreateForm(f => ({ ...f, title: e.target.value }))}
                className="mt-1"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-xs">Type *</Label>
                <Select value={createForm.taskType} onValueChange={(v) => setCreateForm(f => ({ ...f, taskType: v }))}>
                  <SelectTrigger className="mt-1">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="call">Call</SelectItem>
                    <SelectItem value="email">Email</SelectItem>
                    <SelectItem value="quote_follow_up">Quote Follow-up</SelectItem>
                    <SelectItem value="sample_follow_up">Sample Follow-up</SelectItem>
                    <SelectItem value="check_in">Check-in</SelectItem>
                    <SelectItem value="other">Other</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-xs">Priority</Label>
                <Select value={createForm.priority} onValueChange={(v) => setCreateForm(f => ({ ...f, priority: v }))}>
                  <SelectTrigger className="mt-1">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="urgent">Urgent</SelectItem>
                    <SelectItem value="high">High</SelectItem>
                    <SelectItem value="normal">Normal</SelectItem>
                    <SelectItem value="low">Low</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div>
              <Label className="text-xs">Due Date *</Label>
              <Input
                type="date"
                value={createForm.dueDate}
                onChange={(e) => setCreateForm(f => ({ ...f, dueDate: e.target.value }))}
                className="mt-1"
              />
            </div>

            <div>
              <Label className="text-xs">Assign To Lead or Customer *</Label>
              <div className="mt-1 relative">
                <Input
                  placeholder="Search by name or company..."
                  value={contactSearch}
                  onChange={(e) => {
                    setContactSearch(e.target.value);
                    setCreateForm(f => ({ ...f, leadId: "", customerId: "" }));
                  }}
                />
                {(createForm.leadId || createForm.customerId) && (
                  <div className="mt-1.5 flex items-center gap-2 text-xs">
                    <Badge variant="outline" className={createForm.leadId ? "bg-amber-50 text-amber-700 border-amber-200" : "bg-blue-50 text-blue-700 border-blue-200"}>
                      {createForm.leadId ? "Lead" : "Customer"}
                    </Badge>
                    <span className="text-muted-foreground">{contactSearch}</span>
                    <button onClick={() => { setCreateForm(f => ({ ...f, leadId: "", customerId: "" })); setContactSearch(""); }}>
                      <X className="h-3 w-3 text-muted-foreground hover:text-foreground" />
                    </button>
                  </div>
                )}
                {contactSearch.trim().length >= 2 && !createForm.leadId && !createForm.customerId && (
                  <div className="absolute z-50 top-full mt-1 left-0 right-0 bg-white border border-gray-200 rounded-md shadow-lg max-h-48 overflow-y-auto">
                    {contactSearchLoading && (
                      <div className="flex items-center gap-2 px-3 py-2 text-xs text-gray-500">
                        <Loader2 className="h-3 w-3 animate-spin" /> Searching...
                      </div>
                    )}
                    {!contactSearchLoading && contactSearchResults && (
                      <>
                        {contactSearchResults.leads.map((l: ContactSearchLead) => (
                          <button
                            key={`lead-${l.id}`}
                            className="w-full text-left px-3 py-2 hover:bg-gray-50 flex items-center gap-2 text-sm border-b border-gray-100 last:border-0"
                            onClick={() => { setCreateForm(f => ({ ...f, leadId: String(l.id), customerId: "" })); setContactSearch(l.name); }}
                          >
                            <Badge variant="outline" className="bg-amber-50 text-amber-700 border-amber-200 text-xs">Lead</Badge>
                            <span className="font-medium truncate">{l.name}</span>
                            {l.company && <span className="text-xs text-muted-foreground truncate">{l.company}</span>}
                          </button>
                        ))}
                        {contactSearchResults.customers.map((c: ContactSearchCustomer) => {
                          const name = [c.firstName, c.lastName].filter(Boolean).join(" ") || c.company || c.email || "Unknown";
                          return (
                            <button
                              key={`cust-${c.id}`}
                              className="w-full text-left px-3 py-2 hover:bg-gray-50 flex items-center gap-2 text-sm border-b border-gray-100 last:border-0"
                              onClick={() => { setCreateForm(f => ({ ...f, customerId: c.id, leadId: "" })); setContactSearch(name); }}
                            >
                              <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200 text-xs">Customer</Badge>
                              <span className="font-medium truncate">{name}</span>
                              {c.company && <span className="text-xs text-muted-foreground truncate">{c.company}</span>}
                            </button>
                          );
                        })}
                        {contactSearchResults.leads.length === 0 && contactSearchResults.customers.length === 0 && (
                          <div className="px-3 py-2 text-xs text-gray-500">No contacts found</div>
                        )}
                      </>
                    )}
                  </div>
                )}
              </div>
            </div>

            <div>
              <Label className="text-xs">Description (optional)</Label>
              <Textarea
                placeholder="Additional details..."
                value={createForm.description}
                onChange={(e) => setCreateForm(f => ({ ...f, description: e.target.value }))}
                rows={2}
                className="mt-1 resize-none text-sm"
              />
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateTask(false)}>Cancel</Button>
            <Button onClick={handleSubmitCreateTask} disabled={createTaskMutation.isPending}>
              {createTaskMutation.isPending ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Plus className="h-4 w-4 mr-2" />}
              Create Task
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ─── Sub-components ────────────────────────────────────────────────────────────

interface TaskRowsProps {
  tasks: UnifiedTask[];
  onTaskClick: (task: UnifiedTask) => void;
  onComplete: (id: number) => void;
  isCompletePending: boolean;
  getTaskTypeIcon: (type: string | undefined) => ComponentType<{ className?: string }>;
  getPriorityDot: (priority: string | undefined) => string;
  getDueDateStyle: (task: UnifiedTask) => { text: string; className: string };
}

function TaskRows({ tasks, onTaskClick, onComplete, isCompletePending, getTaskTypeIcon, getPriorityDot, getDueDateStyle }: TaskRowsProps) {
  const groups: { label: string; tasks: UnifiedTask[] }[] = [];

  const overdue = tasks.filter(t => t.category === "overdue" && t.source !== "spotlight");
  const today = tasks.filter(t => t.dueDate && isToday(new Date(t.dueDate)) && t.source !== "spotlight");
  const thisWeek = tasks.filter(t => t.dueDate && !isToday(new Date(t.dueDate)) && isThisWeek(new Date(t.dueDate)) && !isPast(new Date(t.dueDate)) && t.source !== "spotlight");
  const upcoming = tasks.filter(t => t.dueDate && !isThisWeek(new Date(t.dueDate)) && !isPast(new Date(t.dueDate)) && t.source !== "spotlight");
  const spotlight = tasks.filter(t => t.source === "spotlight");
  const noDue = tasks.filter(t => !t.dueDate && t.source !== "spotlight");

  if (overdue.length) groups.push({ label: "Overdue", tasks: overdue });
  if (today.length) groups.push({ label: "Due Today", tasks: today });
  if (thisWeek.length) groups.push({ label: "This Week", tasks: thisWeek });
  if (upcoming.length) groups.push({ label: "Upcoming", tasks: upcoming });
  if (noDue.length) groups.push({ label: "No Due Date", tasks: noDue });
  if (spotlight.length) groups.push({ label: "Spotlight", tasks: spotlight });

  if (groups.length === 0) {
    return <EmptyState icon={CheckCircle2} title="All caught up!" description="No tasks in this category." />;
  }

  return (
    <div className="py-2">
      {groups.map((group) => (
        <div key={group.label} className="mb-4">
          <div className="flex items-center gap-2 py-2 mb-1">
            <span className={`text-xs font-semibold uppercase tracking-wider ${
              group.label === "Overdue" ? "text-red-500" :
              group.label === "Due Today" ? "text-amber-600" :
              group.label === "This Week" ? "text-orange-500" :
              group.label === "Spotlight" ? "text-purple-600" :
              "text-gray-400"
            }`}>{group.label}</span>
            <span className="text-xs text-gray-300">·</span>
            <span className="text-xs text-gray-400">{group.tasks.length}</span>
          </div>
          <div className="divide-y divide-gray-100 border border-gray-100 rounded-lg overflow-hidden">
            {group.tasks.map((task) => {
              const TaskIcon = getTaskTypeIcon(task.taskType);
              const isSpotlight = task.source === "spotlight";
              const isOverdue = group.label === "Overdue";
              const dueDateStyle = getDueDateStyle(task);

              return (
                <div
                  key={task.id}
                  className="flex items-center gap-3 px-3 py-2.5 hover:bg-gray-50 cursor-pointer transition-colors group"
                  onClick={() => onTaskClick(task)}
                >
                  {/* Checkbox / Complete button */}
                  <button
                    className="flex-shrink-0 p-0.5 rounded-full hover:bg-gray-200 transition-colors"
                    onClick={(e) => {
                      e.stopPropagation();
                      if (!isSpotlight && typeof task.id === "number") {
                        onComplete(task.id);
                      } else if (!isSpotlight) {
                        onTaskClick(task);
                      }
                    }}
                    disabled={isCompletePending}
                    title="Mark complete"
                  >
                    <Circle className={`h-4 w-4 ${isOverdue ? "text-red-300" : isSpotlight ? "text-purple-300" : "text-gray-300"} group-hover:text-gray-400`} />
                  </button>

                  {/* Type Icon */}
                  <div className={`flex-shrink-0 p-1 rounded ${
                    isSpotlight ? "bg-purple-100" : isOverdue ? "bg-red-50" : "bg-gray-100"
                  }`}>
                    <TaskIcon className={`h-3.5 w-3.5 ${
                      isSpotlight ? "text-purple-600" : isOverdue ? "text-red-500" : "text-gray-500"
                    }`} />
                  </div>

                  {/* Title + Contact */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className={`text-sm font-medium truncate ${
                        isOverdue ? "text-red-700" : "text-gray-800"
                      }`}>
                        {task.title}
                      </span>
                      {isSpotlight && (
                        <span className="flex-shrink-0 text-[10px] font-bold text-purple-600 bg-purple-100 px-1.5 py-0.5 rounded-full">SPOTLIGHT</span>
                      )}
                      {task.isAutoGenerated && (
                        <span className="flex-shrink-0 text-[10px] text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded-full">Auto</span>
                      )}
                    </div>
                    <div className="flex items-center gap-2 mt-0.5">
                      <span className="text-xs text-gray-500 truncate">{task.recordName || task.customerName}</span>
                      {task.recordType && (
                        <span className={`text-[10px] px-1 py-0.5 rounded ${
                          task.recordType === "lead" ? "bg-amber-50 text-amber-600" : "bg-blue-50 text-blue-600"
                        }`}>
                          {task.recordType === "lead" ? "Lead" : "Customer"}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Right side: due date + priority dot + assignee */}
                  <div className="flex-shrink-0 flex items-center gap-3">
                    {task.assignedToName && (
                      <span className="text-xs text-gray-400 hidden sm:block truncate max-w-20">{task.assignedToName}</span>
                    )}
                    {dueDateStyle.text && (
                      <div className="flex items-center gap-1">
                        <Clock className="h-3 w-3 text-gray-300" />
                        <span className={`text-xs ${dueDateStyle.className}`}>{dueDateStyle.text}</span>
                      </div>
                    )}
                    {task.priority && (
                      <div className={`h-2 w-2 rounded-full flex-shrink-0 ${getPriorityDot(task.priority)}`} title={task.priority} />
                    )}
                    <ChevronRight className="h-3.5 w-3.5 text-gray-300 opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}

function EmailsNotRepliedList({ items, onCreateTask, isPending }: {
  items: EmailNotReplied[] | undefined;
  onCreateTask: (id: number | string) => void;
  isPending: boolean;
}) {
  if (!items || items.length === 0) {
    return <EmptyState icon={MailOpen} title="No unreplied emails" description="All pricing and sample emails have received replies." />;
  }
  return (
    <div className="py-2">
      <div className="divide-y divide-gray-100 border border-gray-100 rounded-lg overflow-hidden">
        {items.map((email) => (
          <div key={email.id} className="flex items-center gap-3 px-3 py-3 hover:bg-orange-50/40 transition-colors group">
            <div className="flex-shrink-0 p-1 rounded bg-orange-50">
              <Mail className="h-3.5 w-3.5 text-orange-500" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-gray-800 truncate">{email.subject}</p>
              <div className="flex items-center gap-2 mt-0.5">
                <span className="text-xs text-gray-500">{email.contactName}</span>
                <span className="text-gray-300">·</span>
                <span className="text-xs text-orange-500 font-medium">{email.daysSinceSent}d no reply</span>
                <span className="text-gray-300">·</span>
                <span className="text-xs text-gray-400">{format(new Date(email.sentAt), "MMM d")}</span>
              </div>
            </div>
            <div className="flex-shrink-0 flex items-center gap-2">
              {(email.subject || email.recipientEmail) && (!email.sentBy || email.sentBy.toLowerCase() === currentUserEmail) && (
                <a
                  href={`https://mail.google.com/mail/u/0/#search/${encodeURIComponent(
                    email.subject && email.recipientEmail
                      ? `subject:"${email.subject}" (to:${email.recipientEmail} OR from:${email.recipientEmail})`
                      : email.subject
                        ? `subject:"${email.subject}"`
                        : `to:${email.recipientEmail} OR from:${email.recipientEmail}`
                  )}`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Button variant="ghost" size="sm" className="h-7 text-xs text-blue-500 hover:text-blue-700">
                    <Mail className="h-3 w-3 mr-1" />
                    Gmail
                  </Button>
                </a>
              )}
              {email.recordType && email.recordId && (
                <Link href={email.recordType === "lead" ? `/leads/${email.recordId}` : `/odoo-contacts/${email.recordId}`}>
                  <Button variant="ghost" size="sm" className="h-7 text-xs text-gray-500">
                    <ExternalLink className="h-3 w-3 mr-1" />
                    View
                  </Button>
                </Link>
              )}
              <Button
                size="sm"
                variant="outline"
                className="h-7 text-xs"
                onClick={() => onCreateTask(email.id)}
                disabled={isPending}
              >
                <Plus className="h-3 w-3 mr-1" />
                Task
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function SeqFollowUpList({ items }: { items: SeqFollowUp[] | undefined }) {
  if (!items || items.length === 0) {
    return <EmptyState icon={List} title="No sequence follow-ups" description="No completed email sequences pending a call follow-up." />;
  }
  return (
    <div className="py-2">
      <div className="divide-y divide-gray-100 border border-gray-100 rounded-lg overflow-hidden">
        {items.map((seq) => (
          <div key={seq.id} className="flex items-center gap-3 px-3 py-3 hover:bg-purple-50/30 transition-colors">
            <div className="flex-shrink-0 p-1 rounded bg-purple-50">
              <List className="h-3.5 w-3.5 text-purple-500" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-gray-800 truncate">{seq.campaignName}</p>
              <div className="flex items-center gap-2 mt-0.5">
                <span className="text-xs text-gray-500">{seq.contactName}</span>
                <span className="text-gray-300">·</span>
                <span className="text-xs text-gray-400">Completed {format(new Date(seq.completedAt), "MMM d, yyyy")}</span>
              </div>
            </div>
            <div className="flex-shrink-0 flex items-center gap-2">
              {seq.recordType && seq.recordId && (
                <Link href={seq.recordType === "lead" ? `/leads/${seq.recordId}` : `/odoo-contacts/${seq.recordId}`}>
                  <Button variant="ghost" size="sm" className="h-7 text-xs text-gray-500">
                    <ExternalLink className="h-3 w-3 mr-1" />
                    View
                  </Button>
                </Link>
              )}
              <span className="text-[10px] bg-purple-100 text-purple-600 px-2 py-0.5 rounded-full font-medium">Call needed</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function PressTestList({ items }: { items: PressTestEntry[] | undefined }) {
  if (!items || items.length === 0) {
    return <EmptyState icon={FlaskConical} title="No press test records" description="No press test kits or Samples orders have been recorded yet." />;
  }
  return (
    <div className="py-2">
      <div className="flex items-center gap-4 py-2 text-xs text-gray-400">
        <span className="flex items-center gap-1"><FlaskConical className="h-3 w-3 text-teal-400" /> Manual print</span>
        <span className="flex items-center gap-1"><Building2 className="h-3 w-3 text-sky-400" /> Odoo Sales Order</span>
        <span className="flex items-center gap-1"><Receipt className="h-3 w-3 text-violet-400" /> Odoo Invoice</span>
      </div>
      <div className="divide-y divide-gray-100 border border-gray-100 rounded-lg overflow-hidden">
        {items.map((entry) => {
          const isOdooSO = entry.source === "odoo_sale_order";
          const isOdooInv = entry.source === "odoo_invoice";
          const isOdoo = isOdooSO || isOdooInv;
          const Icon = isOdooSO ? Building2 : isOdooInv ? Receipt : FlaskConical;
          const iconBg = isOdooSO ? "bg-sky-50" : isOdooInv ? "bg-violet-50" : "bg-teal-50";
          const iconColor = isOdooSO ? "text-sky-500" : isOdooInv ? "text-violet-500" : "text-teal-500";
          const sourceLabel = isOdooSO ? "Sales Order" : isOdooInv ? "Invoice" : entry.source === "lead_manual" ? "Lead Log" : "Label Print";

          return (
            <div key={entry.id} className="flex items-center gap-3 px-3 py-3 hover:bg-gray-50 transition-colors">
              <div className={`flex-shrink-0 p-1 rounded ${iconBg}`}>
                <Icon className={`h-3.5 w-3.5 ${iconColor}`} />
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium text-gray-800 truncate">{entry.contactName}</p>
                  <span className="text-[10px] text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded-full">{sourceLabel}</span>
                  {entry.orderNumber && (
                    entry.odooUrl ? (
                      <a href={entry.odooUrl} target="_blank" rel="noopener noreferrer" className="text-xs font-mono text-blue-500 hover:underline flex items-center gap-0.5">
                        <Tag className="h-3 w-3" />{entry.orderNumber}<ExternalLink className="h-2.5 w-2.5" />
                      </a>
                    ) : (
                      <span className="text-xs font-mono text-gray-400"><Tag className="h-3 w-3 inline mr-0.5" />{entry.orderNumber}</span>
                    )
                  )}
                </div>
                <div className="flex items-center gap-2 mt-0.5 text-xs text-gray-400">
                  {entry.sentAt && <span>{format(new Date(entry.sentAt), "MMM d, yyyy")}</span>}
                  {entry.sentByName && <><span className="text-gray-300">·</span><span>{entry.sentByName}</span></>}
                  {entry.quantity && entry.quantity > 1 && <><span className="text-gray-300">·</span><span>Qty: {entry.quantity}</span></>}
                  {entry.notes && <><span className="text-gray-300">·</span><span className="italic truncate max-w-xs">{entry.notes}</span></>}
                </div>
              </div>
              <div className="flex-shrink-0">
                {!isOdoo && entry.customerId && (
                  <Link href={`/odoo-contacts/${entry.customerId}`}>
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-gray-500">
                      <ExternalLink className="h-3 w-3 mr-1" />View
                    </Button>
                  </Link>
                )}
                {!isOdoo && entry.leadId && (
                  <Link href={`/leads/${entry.leadId}`}>
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-gray-500">
                      <ExternalLink className="h-3 w-3 mr-1" />View
                    </Button>
                  </Link>
                )}
                {isOdoo && entry.odooUrl && (
                  <a href={entry.odooUrl} target="_blank" rel="noopener noreferrer">
                    <Button variant="ghost" size="sm" className="h-7 text-xs text-gray-500">
                      <ExternalLink className="h-3 w-3 mr-1" />Odoo
                    </Button>
                  </a>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function EmptyState({ icon: Icon, title, description }: { icon: ComponentType<{ className?: string }>; title: string; description: string }) {
  return (
    <div className="flex flex-col items-center justify-center h-52 text-center">
      <div className="h-12 w-12 rounded-full bg-gray-100 flex items-center justify-center mb-3">
        <Icon className="h-6 w-6 text-gray-400" />
      </div>
      <p className="text-sm font-medium text-gray-700">{title}</p>
      <p className="text-xs text-gray-400 mt-1 max-w-xs">{description}</p>
    </div>
  );
}
