import { storage } from "./storage";
import type { InsertCustomerActivityEvent, InsertFollowUpTask, InsertProductExposureLog, FollowUpConfig } from "@shared/schema";

async function getConfigForEventType(eventType: string): Promise<FollowUpConfig | undefined> {
  const configs = await storage.getFollowUpConfig();
  return configs.find(c => c.eventType === eventType);
}

interface AutoTrackQuoteParams {
  customerId: string;
  quoteNumber: string;
  quoteId?: number;
  totalAmount: string;
  itemCount: number;
  quoteItems: any[];
  sentVia: string;
  userId?: string;
  userName?: string;
}

interface AutoTrackPriceListParams {
  customerId: string;
  quoteNumber: string;
  category: string;
  tier: string;
  itemCount: number;
  priceListItems: any[];
  userId?: string;
  userName?: string;
}

interface AutoTrackSampleParams {
  customerId: string;
  sampleRequestId: number;
  productId?: number;
  productName?: string;
  status: string;
  trackingNumber?: string;
  userId?: string;
  userName?: string;
}

export async function autoTrackQuoteSent(params: AutoTrackQuoteParams): Promise<void> {
  const { customerId, quoteNumber, quoteId, totalAmount, itemCount, quoteItems, sentVia, userId, userName } = params;
  
  try {
    const now = new Date();
    const eventTitle = `Quote #${quoteNumber} sent via ${sentVia}`;
    const eventDescription = `Quote for $${parseFloat(totalAmount).toFixed(2)} with ${itemCount} items`;
    
    const activityEvent = await storage.createActivityEvent({
      customerId,
      eventType: 'quote_sent',
      title: eventTitle,
      description: eventDescription,
      sourceType: 'auto',
      sourceId: quoteId?.toString() || quoteNumber,
      sourceTable: 'sent_quotes',
      amount: totalAmount,
      itemCount,
      createdBy: userId,
      createdByName: userName,
      eventDate: now,
    });
    
    const config = await getConfigForEventType('quote_sent');
    if (config && config.isEnabled) {
      const dueDate = new Date(now);
      dueDate.setDate(dueDate.getDate() + (config.defaultDelayDays || 1));
      
      await storage.createFollowUpTask({
        customerId,
        title: config.taskTitle?.replace('{event}', `Quote #${quoteNumber}`) || `Follow up on Quote #${quoteNumber}`,
        description: config.taskDescription || `Check if customer received the quote and has any questions. Total: $${parseFloat(totalAmount).toFixed(2)}`,
        taskType: 'quote_follow_up',
        priority: config.defaultPriority || 'normal',
        status: 'pending',
        dueDate,
        sourceEventId: activityEvent.id,
        sourceType: 'quote',
        sourceId: quoteNumber,
        assignedTo: userId,
        assignedToName: userName,
        isAutoGenerated: true,
      });
    }
    
    if (quoteItems && quoteItems.length > 0) {
      for (const item of quoteItems) {
        await storage.createProductExposure({
          customerId,
          productId: item.productId || null,
          productName: item.productType || item.itemCode || 'Unknown Product',
          productCategory: item.category,
          exposureType: 'quote',
          sourceId: quoteNumber,
          sharedBy: userId,
          sharedByName: userName,
        });
      }
    }
    
    console.log(`✅ Auto-tracked quote ${quoteNumber} for customer ${customerId}`);
  } catch (error) {
    console.error('❌ Error auto-tracking quote:', error);
  }
}

export async function autoTrackPriceListSent(params: AutoTrackPriceListParams): Promise<void> {
  const { customerId, quoteNumber, category, tier, itemCount, priceListItems, userId, userName } = params;
  
  try {
    const now = new Date();
    const eventTitle = `Price List #${quoteNumber} generated`;
    const eventDescription = `Price list for ${category} - ${tier} tier with ${itemCount} items`;
    
    const activityEvent = await storage.createActivityEvent({
      customerId,
      eventType: 'price_list_sent',
      title: eventTitle,
      description: eventDescription,
      sourceType: 'auto',
      sourceId: quoteNumber,
      sourceTable: 'sent_quotes',
      itemCount,
      createdBy: userId,
      createdByName: userName,
      eventDate: now,
    });
    
    const config = await getConfigForEventType('price_list_sent');
    if (config && config.isEnabled) {
      const dueDate = new Date(now);
      dueDate.setDate(dueDate.getDate() + (config.defaultDelayDays || 2));
      
      await storage.createFollowUpTask({
        customerId,
        title: config.taskTitle?.replace('{event}', `Price List #${quoteNumber}`) || `Follow up on Price List #${quoteNumber}`,
        description: config.taskDescription || `Check if customer reviewed the ${category} price list and discuss products of interest`,
        taskType: 'price_list_follow_up',
        priority: config.defaultPriority || 'normal',
        status: 'pending',
        dueDate,
        sourceEventId: activityEvent.id,
        sourceType: 'price_list',
        sourceId: quoteNumber,
        assignedTo: userId,
        assignedToName: userName,
        isAutoGenerated: true,
      });
    }
    
    console.log(`✅ Auto-tracked price list ${quoteNumber} for customer ${customerId}`);
  } catch (error) {
    console.error('❌ Error auto-tracking price list:', error);
  }
}

export async function autoTrackSampleShipped(params: AutoTrackSampleParams): Promise<void> {
  const { customerId, sampleRequestId, productId, productName, status, trackingNumber, userId, userName } = params;
  
  try {
    const now = new Date();
    const eventType = status === 'shipped' ? 'sample_shipped' : 
                      status === 'delivered' ? 'sample_delivered' : 
                      status === 'pending' ? 'sample_requested' : 'sample_feedback';
    
    const eventTitle = status === 'shipped' 
      ? `Sample shipped: ${productName}${trackingNumber ? ` (Tracking: ${trackingNumber})` : ''}`
      : status === 'delivered'
        ? `Sample delivered: ${productName}`
        : status === 'pending'
          ? `Sample requested: ${productName}`
          : `Sample feedback received: ${productName}`;
    
    const activityEvent = await storage.createActivityEvent({
      customerId,
      eventType,
      title: eventTitle,
      description: `Sample request ID: ${sampleRequestId}`,
      sourceType: 'auto',
      sourceId: sampleRequestId.toString(),
      sourceTable: 'sample_requests',
      productId,
      productName,
      createdBy: userId,
      createdByName: userName,
      eventDate: now,
    });
    
    if (status === 'shipped' || status === 'delivered') {
      const config = await getConfigForEventType(eventType);
      if (config && config.isEnabled) {
        const dueDate = new Date(now);
        dueDate.setDate(dueDate.getDate() + (config.defaultDelayDays || (status === 'shipped' ? 5 : 2)));
        
        await storage.createFollowUpTask({
          customerId,
          title: config.taskTitle?.replace('{event}', productName || 'Sample') || 
                 `Follow up on ${productName || 'Sample'} ${status === 'shipped' ? 'delivery' : 'test results'}`,
          description: config.taskDescription || 
                      (status === 'shipped' 
                        ? `Sample shipped. Check if customer received it and schedule press test.` 
                        : `Sample delivered. Follow up on test results and press feedback.`),
          taskType: 'sample_follow_up',
          priority: config.defaultPriority || 'high',
          status: 'pending',
          dueDate,
          sourceEventId: activityEvent.id,
          sourceType: 'sample',
          sourceId: sampleRequestId.toString(),
          assignedTo: userId,
          assignedToName: userName,
          isAutoGenerated: true,
        });
      }
    }
    
    if (productName) {
      await storage.createProductExposure({
        customerId,
        productId: productId || null,
        productName,
        exposureType: 'sample',
        sourceId: sampleRequestId.toString(),
        sharedBy: userId,
        sharedByName: userName,
      });
    }
    
    console.log(`✅ Auto-tracked sample ${sampleRequestId} (${status}) for customer ${customerId}`);
  } catch (error) {
    console.error('❌ Error auto-tracking sample:', error);
  }
}

export async function autoTrackManualActivity(params: {
  customerId: string;
  eventType: string;
  title: string;
  description?: string;
  userId?: string;
  userName?: string;
  createFollowUp?: boolean;
  followUpDays?: number;
}): Promise<void> {
  const { customerId, eventType, title, description, userId, userName, createFollowUp, followUpDays } = params;
  
  try {
    const now = new Date();
    
    const activityEvent = await storage.createActivityEvent({
      customerId,
      eventType,
      title,
      description,
      sourceType: 'manual',
      createdBy: userId,
      createdByName: userName,
      eventDate: now,
    });
    
    if (createFollowUp) {
      const dueDate = new Date(now);
      dueDate.setDate(dueDate.getDate() + (followUpDays || 1));
      
      await storage.createFollowUpTask({
        customerId,
        title: `Follow up: ${title}`,
        description,
        taskType: 'manual_follow_up',
        priority: 'normal',
        status: 'pending',
        dueDate,
        sourceEventId: activityEvent.id,
        sourceType: 'manual',
        assignedTo: userId,
        assignedToName: userName,
        isAutoGenerated: false,
      });
    }
    
    console.log(`✅ Tracked manual activity for customer ${customerId}: ${title}`);
  } catch (error) {
    console.error('❌ Error tracking manual activity:', error);
  }
}

export async function findCustomerIdByEmail(email: string): Promise<string | null> {
  try {
    const customers = await storage.getCustomers();
    const customer = customers.find(c => c.email?.toLowerCase() === email.toLowerCase());
    return customer?.id || null;
  } catch (error) {
    console.error('Error finding customer by email:', error);
    return null;
  }
}

export async function findCustomerIdByName(name: string): Promise<string | null> {
  try {
    const customers = await storage.getCustomers();
    const normalizedName = name.toLowerCase().trim();
    
    const customer = customers.find(c => {
      const fullName = `${c.firstName || ''} ${c.lastName || ''}`.toLowerCase().trim();
      const company = (c.company || '').toLowerCase().trim();
      return fullName === normalizedName || company === normalizedName || 
             fullName.includes(normalizedName) || company.includes(normalizedName);
    });
    
    return customer?.id || null;
  } catch (error) {
    console.error('Error finding customer by name:', error);
    return null;
  }
}
